config/routes.rb
Rails.application.routes.draw do

  resources :empire_master_no_matches do
    collection {post :import}
  end
  resources :empire_master_matches do
    collection {post :import}
  end
  resources :master_ea_double_accounts do
    collection {post :import}
  end
  resources :master_cpa_double_accounts do
    collection {post :import}
  end
  resources :master_ea_no_matches do
    collection {post :import}
  end
  resources :master_ea_matches do
    collection {post :import}
  end
  resources :master_eas do
    collection {post :import}
    collection do
      get 'search'
      get 'no_mail_ea'
      get 'ea_customers'
    end
  end
  resources :master_cpa_matches do
    collection {post :import}
  end
  resources :master_cpa_no_matches do
    collection {post :import}
  end
  resources :master_cpas do
    collection {post :import}
    collection do
      get 'search'
      get 'no_mail_cpa'
      get 'cpa_customers'
    end
  end
  resources :empire_rc_states do
    collection {
      get 'upload_list'
    }
  end
  resources :email_records
  resources :email_exports
  resources :quotes
  resources :sequoia_customer_matches
  resources :postcard_records
  resources :postcard_exports

  resources :empire_master_lists do
    collection {post :import}
    collection do
      get 'ny'
      get 'ny_marketing'
      get 'ny_week'
    end
  end
  resources :empire_state_lists
  resources :s_customers do
    collection {post :import}
    collection do
      get 'data'
      get 'rc_marketing'
      get 'sales'
    end
  end
  resources :empire_customers do
    collection {post :import}
    collection do
      get 'exports'
      get 'sales'
      get 'rc_marketing'
      get 'b_exp'
      get 'rolling_email_export'
    end
  end

  resources :master_lists do
    collection {post :import}
    collection do
      get 'remove_all'
      get 'no_mail_add'
      get 'no_mail'
      get 'mailings'
    end
  end

  resources :mailing_empire_nms do
    collection {post :import}
    collection do
      get 'remove_all'
      get 'no_mail'
      get 'data'
    end
  end

  resources :sales do
    collection {post :import}
  end
  resources :task_deadlines
  resources :course_creation_tasks
  resources :empire_courses
  resources :course_creation_templetes
  resources :calendars
  resources :live_chat_answers
  resources :cpe_due_dates do
    collection {post :import}
    end

  resources :course_comments
  resources :call_logs do
    collection do
      get 'add_new_select_topic'
    end
  end
  resources :seq_no_mails do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end
  # get 'exam_results/index'
  # get 'exam_results/import' => 'exam_results#my_import'
  resources :exam_results do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end
  get 'exam_results/index0'
  resources :email_campaigns
  resources :inventories
  resources :postcard_mailings
  resources :tx_royalties
  resources :empire_mailings
  resources :mailings do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end
  resources :tasks
  # resources :sequoia_customers
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'sequoia/dash'
  get 'sequoia/dash_ashley'
  get 'sequoia/dash_michael'
  get 'sequoia/dash_sabrina'
  get 'sequoia/dash_kyle'
  get 'sequoia/dash_john'
  get 'sequoia/dash_christian'
  get 'sequoia/dash_james'
  get 'sequoia/dash_extra'
  get 'sequoia/s_data'

  resources :date_fields
  resources :pes_courses do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end

  resources :postcard_returns
  get 'sales_report/postcard_return_stats'
  get 'sales_report/call_log_stats'
  get 'sales_report/sequoia_sales'
  get 'sales_report/sequoia_exams'

  get 'test_pages/test_1'

  get 'sales_report/course_status'
  get 'sequoia_customers/index'

  get 'sequoia_customers/import' => 'sequoia_customers#my_import'
  resources :sequoia_customers do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end

  get 'sequoia_exams/import' => 'sequoia_exams#my_import'
  resources :sequoia_exams do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end

  get 'empire/dash'

  get 'empire/dash'
  resources :copyrights
  devise_for :users
  # get 'updatesheets/:id/', to: redirect("/updatesheets")
  resources :updatesheets
  resources :datasheets do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end

  root :to => 'home#index'

  # user_signed_in? && current_user.email == 'austin@sequoiacpe.com' ? root :to => "sequoia#dash" : ''
  # user_signed_in? && current_user.email == 'ashley@sequoiacpe.com' ? root :to => "sequoia#dash_ashley" : ''
  # user_signed_in? && current_user.email == 'kyle@sequoiacpe.com' ? root :to => "datasheets#index" : ''
  # user_signed_in? && current_user.email == 'micheal@sequoiacpe.com' ? root :to => "datasheets#index" : ''
  # root :to => "datasheets#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/pes_courses_controller.rb
class PesCoursesController < ApplicationController
  before_action :set_pes_course, only: [:show, :edit, :update, :destroy, :change]

  # GET /pes_courses
  # GET /pes_courses.json

  def index
    @pes_courses = PesCourse.order('active DESC').order(:pes_number)
    @date_fields = DateField.all

    respond_to do |format|
      format.html
      format.csv { send_data @pes_courses.to_csv, filename: "pes_course-#{Date.today}.csv" }
    end

    course_counter

  end

  # GET /pes_courses/1
  # GET /pes_courses/1.json
  def show
  end

  # GET /pes_courses/new
  def new
    @pes_course = PesCourse.new
    form_collections
  end

  # GET /pes_courses/1/edit
  def edit
    form_collections
  end

  # POST /pes_courses
  # POST /pes_courses.json
  def create
    @pes_course = PesCourse.new(pes_course_params)

    respond_to do |format|
      if @pes_course.save
        format.html { redirect_to @pes_course, notice: 'Pes course was successfully created.' }
        format.json { render :show, status: :created, location: @pes_course }
      else
        format.html { render :new }
        format.json { render json: @pes_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pes_courses/1
  # PATCH/PUT /pes_courses/1.json
  def update
    respond_to do |format|
      if @pes_course.update(pes_course_params)
        format.html { redirect_to @pes_course, notice: 'Pes course was successfully updated.' }
        format.json { render :show, status: :ok, location: @pes_course }
      else
        format.html { render :edit }
        format.json { render json: @pes_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pes_courses/1
  # DELETE /pes_courses/1.json
  def destroy
    @pes_course.destroy
    respond_to do |format|
      format.html { redirect_to pes_courses_url, notice: 'Pes course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_all
    PesCourse.delete_all
    flash[:notice] = "All Records Removed"
    redirect_to pes_courses_path
  end

  def import #Uploading CSV function
    PesCourse.import(params[:file])
    redirect_to pes_courses_path, notice: "Upload Complete"
  end

  def form_collections
    @course_tags = ['N/A', 'New', 'Top Seller', 'Hot Topic', 'Popular']
    @course_cat = ['Accounting', 'Auditing', 'Taxes', 'Management Services', 'Business Law', 'Business Management', 'Communications', 'Computer Applications', 'Finance', 'Personnel/Human Resources', 'Ethics']
  end

  def course_counter
    @active_pes_courses = PesCourse.where('active = true').count
    @inactive_pes_courses = PesCourse.where('active = false').count
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pes_course
      @pes_course = PesCourse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pes_course_params
      params.require(:pes_course).permit(:pes_number, :category, :hours, :active, :title, :tag, :date_added, :date_removed, :extra_s, :extra_i, :extra_b, :extra_d)
    end
end

app/helpers/pes_courses_helper.rb
module PesCoursesHelper
end

app/views/pes_courses/_form.html.erb
<%= simple_form_for(@pes_course) do |f| %>
<br>
  <%= f.error_notification %>
  <div class="row">
    <div class="col-lg-offset-3">
      <%= f.input :extra_d, label: 'PES List Update' %>
    </div>
  </div>
  <div class="col-lg-offset-3 col-lg-6 well well-white">
  <br>
    <div class="row">
      <div class="col-lg-3">
        <%= f.input :pes_number, label: 'PES Number'%>
      </div>
      <div class="col-lg-3">
        <%= f.input :hours, label: 'Hours' %>
      </div>
      <div class="col-lg-3">
        <%= f.input :category, label: 'Category', collection: @course_cat , as: :select %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-9">
        <%= f.input :title, label: 'Course Title' %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3">
        <%= f.input :tag, label: 'Course Tag', collection: @course_tags , as: :select %>
      </div>
    </div>
<%= f.input :active, as: :hidden, label: 'Is Course Currently Active?', as: :radio_buttons, :checked => ['Yes', true] %>
<%= f.input :date_added, as: :hidden, label: 'Course first seen on PES' %>
<%= f.input :date_removed, as: :hidden, label: 'Course no longer active' %>
<br>
<%= f.button :submit, 'Submit', class: 'btn btn-primary' %>
</div>

<% end %>

app/views/pes_courses/_form0.html.erb
<%= simple_form_for(@pes_course) do |f| %>

  <%= f.input :active %>

  <% end %>

app/views/pes_courses/_form_edit.html.erb
<%= simple_form_for(@pes_course) do |f| %>
</br>
  <%= f.error_notification %>
  <div class="col-lg-offset-4 col-lg-4 well well-white">
  </br>
    <div class="row">
      <div class="col-lg-4">
        <%= f.input :pes_number, label: 'PES Number'%>
      </div>
      <div class="col-lg-4">
        <%= f.input :hours, label: 'Hours' %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <%= f.input :tag, label: 'Course Tag', collection: @course_tags , as: :select %>
      </div>
      <div class="col-lg-6">
        <%= f.input :category, label: 'Category' %>
      </div>
    </div>
<%= f.input :title, label: 'Course Title' %>
<%= f.input :active, label: 'Is Course Currently Active?', as: :radio_buttons %>
<!-- <%= f.input :date_added, label: 'Course first seen on PES' %> -->
<%= f.input :date_removed, label: 'No longer active Date', hint: 'set to the day you noticed the course removed (today)' %>
</br>
<%= f.button :submit, 'Submit', class: 'btn btn-primary' %>
</div>

<% end %>

app/views/pes_courses/_form_old.html.erb
<%= form_with(model: pes_course, local: true) do |form| %>
  <% if pes_course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pes_course.errors.count, "error") %> prohibited this pes_course from being saved:</h2>

      <ul>
      <% pes_course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pes_number %>
    <%= form.number_field :pes_number, id: :pes_course_pes_number %>
  </div>

  <div class="field">
    <%= form.label :tag %>
    <%= form.select :tag, ['N/A', 'New', 'Top Seller', 'Hot Topic', 'Popular'], id: :pes_course_tag %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :pes_course_category %>
  </div>

  <div class="field">
    <%= form.label :hours %>
    <%= form.number_field :hours, id: :pes_course_hours %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :pes_course_title %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :pes_course_active, value: true %>
  </div>

  <div class="field">
    <%= form.label :date_added %>
    <%= form.date_select :date_added, id: :pes_course_date_added, value: true %>
  </div>

  <div class="field">
    <%= form.label :date_removed %>
    <%= form.date_select :date_removed, id: :pes_course_date_removed, value: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pes_courses/edit.html.erb
</br>
<div class="page-header ">
  <h1 class="text-center">Editing Pes Course</h1>
</div>

</br>
  <div class="col-lg-offset-4">
  <%= link_to 'PES Course Index', pes_courses_path, class: 'btn btn-default' %> <%= link_to 'Show', @pes_course, class: 'btn btn-default' %>
</div>

<%= render 'form_edit', pes_course: @pes_course %>

app/views/pes_courses/index.html.erb
<p id="notice"><%= notice %></p>

<div class="well jumbotron text-center">
<h1>Pes Courses</h1>
</div>

</br>
<%= link_to 'New Pes Course', new_pes_course_path, class: 'btn btn-primary' %>
</br>

<h3>Last Updated:
<% @date_fields.each do |date_field| %>
  <u><%= date_field.date1.strftime('%-m/%d/%Y') %></u>
</h3>

  <h4><%= link_to 'Update', edit_date_field_path(date_field) %></h4>

<% end %>

</br>
<h5>Active PES Courses: <%= @active_pes_courses %></h5>
<h5>Inactive PES Courses: <%= @inactive_pes_courses %></h5>
</br>
<div class="row">
  <div class="col-md-3">
    <input class="form-control" id="myInput" type="text" placeholder="Search PES Courses">
    <%= link_to 'Export(csv)', pes_courses_path('csv'), class: 'btn btn-default' %>
  </div>
</div>
</br>
<p class=""><a target="_blank" href="https://www.mypescpe.com/search-cpe-courses">Search PES Course By Number</a></p>
</br>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Number</th>
      <th>Status</th>
      <th>Link</th>
      <th>Tag</th>
      <th>Category</th>
      <th>Hours</th>
      <th>Title</th>
      <th>Added</th>
      <th>Removed</th>
      <!-- <th>Status</th> -->
      <!-- <th>Active</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="myTable">
    <% @pes_courses.each do |pes_course| %>
      <tr>
        <td><%= pes_course.pes_number %></td>

        <% if pes_course.active == true %>
          <td> <%= link_to 'Active', edit_pes_course_path(pes_course) %></td>
        <% elsif %>
          <td> <%= link_to 'Unlisted', edit_pes_course_path(pes_course) %></td>
        <% end %>

        <td><a target="_blank" href="https://www.mypescpe.com/panel.account/OPEN/purchase.manager/indexOpenItem.cmc?&file=FULLpes&sku=<%= pes_course.pes_number %>&view=1A&ste="> PES </a></td>
        <td><%= pes_course.tag %></td>
        <td><%= pes_course.category %></td>
        <td><%= pes_course.hours %></td>
        <td><%= pes_course.title %></td>
        <!-- <td><%#= pes_course.date_added %></td> -->
        <% if pes_course.date_added.blank? %>
          <td>nil</td>
        <% elsif pes_course.date_added.present? ? pes_course.date_added.strftime('%-m/%-d/%y') == '1/1/13' : ''%>
          <td>Unknown</td>
        <% elsif pes_course.date_added.present? ? pes_course.date_added.strftime('%-m/%-d/%y') == '8/21/18' : ''%>
          <td>Orginal</td>
        <% elsif %>
          <td><%= pes_course.date_added.present? ? pes_course.date_added.strftime('%-m/%-d/%y') : 'missing' %></td>
        <% end %>
        <td><%= pes_course.active == false ? 'N/A' : pes_course.date_removed.strftime('%-m/%-d/%y') == '1/1/13' ? 'Unknown' : pes_course.date_removed %></td>

        <td><%= link_to 'Remove', pes_course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Upload CSV File</h3>
  <%= form_tag import_pes_courses_path, multipart: true do %>
  <%= file_field_tag :file %>
</br>
  <%= submit_tag 'Upload', class: 'btn btn-primary' %>
<% end %>
</br>
<%= link_to "Remove All", remove_all_pes_courses_path, :method => :get %>

app/views/pes_courses/new.html.erb
</br>
<div class="page-header ">
  <h1 class="text-center">PES Course</h1>
</div>

</br>
  <div class="col-lg-offset-3">
  <%= link_to 'PES Course Index', pes_courses_path, class: 'btn btn-default' %>
</div>

<%= render 'form', pes_course: @pes_course %>

app/views/pes_courses/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header ">
</br>
  <h1 class="text-center"><strong>PES Course - <%= @pes_course.pes_number %></strong> </br><small>PES Active: <%= @pes_course.active %></small></h1>
  <div class="col-lg-offset-2">
    <%= link_to 'Back to Index', pes_courses_path, class: 'btn btn-default' %> <%= link_to 'Edit Entry', edit_pes_course_path(@pes_course), class: 'btn btn-default' %>
  </div>
</div>
</br>

<div class="col-lg-offset-2">
<p>
  <strong>Pes Number:</strong>
  <%= @pes_course.pes_number %>
</p>

<p>
  <strong>Category:</strong>
  <%= @pes_course.category %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @pes_course.tag %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @pes_course.hours %>
</p>

<p>
  <strong>Title:</strong>
  <%= @pes_course.title %>
</p>

<p>
  <strong>Active:</strong>
  <%= @pes_course.active %>
</p>
<p>
  <strong>Date Added:</strong>
  <%= @pes_course.date_added.blank? == false ? @pes_course.date_added.strftime('%-m/%-d/%y') : 'n/a' %>
</p>
<p>
  <strong>Date Removed:</strong>
  <%= @pes_course.date_removed.blank? == false ? @pes_course.date_removed.strftime('%-m/%-d/%y') : 'n/a' %>
</p>
</div>

<!-- <%= link_to 'Edit', edit_pes_course_path(@pes_course) %> |
<%= link_to 'Back', pes_courses_path %> -->