config/routes.rb
Rails.application.routes.draw do

  resources :empire_master_no_matches do
    collection {post :import}
  end
  resources :empire_master_matches do
    collection {post :import}
  end
  resources :master_ea_double_accounts do
    collection {post :import}
  end
  resources :master_cpa_double_accounts do
    collection {post :import}
  end
  resources :master_ea_no_matches do
    collection {post :import}
  end
  resources :master_ea_matches do
    collection {post :import}
  end
  resources :master_eas do
    collection {post :import}
    collection do
      get 'search'
      get 'no_mail_ea'
      get 'ea_customers'
    end
  end
  resources :master_cpa_matches do
    collection {post :import}
  end
  resources :master_cpa_no_matches do
    collection {post :import}
  end
  resources :master_cpas do
    collection {post :import}
    collection do
      get 'search'
      get 'no_mail_cpa'
      get 'cpa_customers'
    end
  end
  resources :empire_rc_states do
    collection {
      get 'upload_list'
    }
  end
  resources :email_records
  resources :email_exports
  resources :quotes
  resources :sequoia_customer_matches
  resources :postcard_records
  resources :postcard_exports

  resources :empire_master_lists do
    collection {post :import}
    collection do
      get 'ny'
      get 'ny_marketing'
      get 'ny_week'
    end
  end
  resources :empire_state_lists
  resources :s_customers do
    collection {post :import}
    collection do
      get 'data'
      get 'rc_marketing'
      get 'sales'
    end
  end
  resources :empire_customers do
    collection {post :import}
    collection do
      get 'exports'
      get 'sales'
      get 'rc_marketing'
      get 'b_exp'
      get 'rolling_email_export'
    end
  end

  resources :master_lists do
    collection {post :import}
    collection do
      get 'remove_all'
      get 'no_mail_add'
      get 'no_mail'
      get 'mailings'
    end
  end

  resources :mailing_empire_nms do
    collection {post :import}
    collection do
      get 'remove_all'
      get 'no_mail'
      get 'data'
    end
  end

  resources :sales do
    collection {post :import}
  end
  resources :task_deadlines
  resources :course_creation_tasks
  resources :empire_courses
  resources :course_creation_templetes
  resources :calendars
  resources :live_chat_answers
  resources :cpe_due_dates do
    collection {post :import}
    end

  resources :course_comments
  resources :call_logs do
    collection do
      get 'add_new_select_topic'
    end
  end
  resources :seq_no_mails do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end
  # get 'exam_results/index'
  # get 'exam_results/import' => 'exam_results#my_import'
  resources :exam_results do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end
  get 'exam_results/index0'
  resources :email_campaigns
  resources :inventories
  resources :postcard_mailings
  resources :tx_royalties
  resources :empire_mailings
  resources :mailings do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end
  resources :tasks
  # resources :sequoia_customers
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'sequoia/dash'
  get 'sequoia/dash_ashley'
  get 'sequoia/dash_michael'
  get 'sequoia/dash_sabrina'
  get 'sequoia/dash_kyle'
  get 'sequoia/dash_john'
  get 'sequoia/dash_christian'
  get 'sequoia/dash_james'
  get 'sequoia/dash_extra'
  get 'sequoia/s_data'

  resources :date_fields
  resources :pes_courses do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end

  resources :postcard_returns
  get 'sales_report/postcard_return_stats'
  get 'sales_report/call_log_stats'
  get 'sales_report/sequoia_sales'
  get 'sales_report/sequoia_exams'

  get 'test_pages/test_1'

  get 'sales_report/course_status'
  get 'sequoia_customers/index'

  get 'sequoia_customers/import' => 'sequoia_customers#my_import'
  resources :sequoia_customers do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end

  get 'sequoia_exams/import' => 'sequoia_exams#my_import'
  resources :sequoia_exams do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end

  get 'empire/dash'

  get 'empire/dash'
  resources :copyrights
  devise_for :users
  # get 'updatesheets/:id/', to: redirect("/updatesheets")
  resources :updatesheets
  resources :datasheets do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end

  root :to => 'home#index'

  # user_signed_in? && current_user.email == 'austin@sequoiacpe.com' ? root :to => "sequoia#dash" : ''
  # user_signed_in? && current_user.email == 'ashley@sequoiacpe.com' ? root :to => "sequoia#dash_ashley" : ''
  # user_signed_in? && current_user.email == 'kyle@sequoiacpe.com' ? root :to => "datasheets#index" : ''
  # user_signed_in? && current_user.email == 'micheal@sequoiacpe.com' ? root :to => "datasheets#index" : ''
  # root :to => "datasheets#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/datasheet.rb
class Datasheet < ApplicationRecord
  self.primary_key = 'seq_number'
  has_many :Updatesheets
  has_many :CourseComments
  has_one :Copyrights
  belongs_to :pes_course, foreign_key: 'pes_number'
  validates :seq_number, :presence => true, :uniqueness => true

  def self.to_csv # Export to csv function
    attributes = %w{seq_number seq_version category seq_title hours pub_date seq_update seq_original_list active drop_date drop_reason pes_listed pes_number pes_version needs_approval has_approval approval_info course_note extra_note}
    CSV.generate(headers: true) do |csv|
      csv << attributes

        all.each do |datasheet|
          csv << attributes.map{ |attr| datasheet.send(attr) }
        end
    end
  end

  def self.import(file) # import to cvs function
    CSV.foreach(file.path, headers: true) do |row|
    Datasheet.create! row.to_hash
  end
end


end

app/controllers/datasheets_controller.rb
class DatasheetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_datasheet, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction #sortable header columns

  # GET /datasheets
  # GET /datasheets.json
  def index
    @datasheets = Datasheet.order(sort_column + " " + sort_direction) #sortable header columns
    @datasheet_all = Datasheet.all

    respond_to do |format|
      format.html
      format.csv { send_data @datasheets.to_csv, filename: "datasheet-#{Date.today}.csv" }
    end
    course_counter
  end

  # GET /datasheets/1
  # GET /datasheets/1.json
  def show
    old_version_pub_dates
  end

  # GET /datasheets/new
  def new
    @datasheet = Datasheet.new
  end

  # GET /datasheets/1/edit
  def edit
  end

  # POST /datasheets
  # POST /datasheets.json
  def create
    @datasheet = Datasheet.new(datasheet_params)

    respond_to do |format|
      if @datasheet.save
        format.html { redirect_to @datasheet, notice: 'Datasheet was successfully created.' }
        format.json { render :show, status: :created, location: @datasheet }
      else
        format.html { render :new }
        format.json { render json: @datasheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /datasheets/1
  # PATCH/PUT /datasheets/1.json
  def update
    respond_to do |format|
      if @datasheet.update(datasheet_params)
        format.html { redirect_to @datasheet, notice: 'Datasheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @datasheet }
      else
        format.html { render :edit }
        format.json { render json: @datasheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datasheets/1
  # DELETE /datasheets/1.json
  def destroy
    @datasheet.destroy
    respond_to do |format|
      format.html { redirect_to datasheets_url, notice: 'Datasheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_all
    Datasheet.delete_all
    flash[:notice] = "All Records Removed"
    redirect_to datasheets_path
  end

  def import #Uploading CSV function
    Datasheet.import(params[:file])
    redirect_to datasheets_path, notice: "Upload Complete"
  end

  def course_counter

    @active_courses = []
    @active_courses_ethics = []

    @datasheet_all.each do |datasheet|
      datasheet.active == true && datasheet.seq_number < 9000 ? @active_courses.push(datasheet['seq_number']) : ''
      datasheet.active == true && datasheet.seq_number >= 9000 ? @active_courses_ethics.push(datasheet['seq_number']) : ''
    end
  end

  def old_version_pub_dates

    @array = []

    if @datasheet.version_a.blank? == false
      # @datasheet.seq_version > 'A' ? @array.push((@datasheet.pub_date - @datasheet.version_a).to_i) : ''
       @datasheet.seq_version > 'B' ? @array.push((@datasheet.version_b - @datasheet.version_a).to_i) : ''
       @datasheet.seq_version > 'C' ? @array.push((@datasheet.version_c - @datasheet.version_b).to_i) : ''
       @datasheet.seq_version > 'D' ? @array.push((@datasheet.version_d - @datasheet.version_c).to_i) : ''
       @datasheet.seq_version > 'E' ? @array.push((@datasheet.version_e - @datasheet.version_d).to_i) : ''
       @datasheet.seq_version > 'F' ? @array.push((@datasheet.version_f - @datasheet.version_e).to_i) : ''
       @datasheet.seq_version > 'G' ? @array.push((@datasheet.version_g - @datasheet.version_f).to_i) : ''
       @datasheet.seq_version > 'H' ? @array.push((@datasheet.version_h - @datasheet.version_g).to_i) : ''
       @datasheet.seq_version > 'I' ? @array.push((@datasheet.version_i - @datasheet.version_h).to_i) : ''
       @datasheet.seq_version > 'J' ? @array.push((@datasheet.version_j - @datasheet.version_i).to_i) : ''
       @datasheet.seq_version > 'K' ? @array.push((@datasheet.version_k - @datasheet.version_j).to_i) : ''
       @datasheet.seq_version > 'L' ? @array.push((@datasheet.version_l - @datasheet.version_k).to_i) : ''
       @datasheet.seq_version > 'M' ? @array.push((@datasheet.version_m - @datasheet.version_l).to_i) : ''
       @datasheet.seq_version > 'N' ? @array.push((@datasheet.version_n - @datasheet.version_m).to_i) : ''
       @array.length > 0 ? @time_between = @array.sum / @array.length : 'nil'
     end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datasheet
      @datasheet = Datasheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def datasheet_params
      params.require(:datasheet).permit(:seq_number, :seq_version, :category, :seq_title, :hours, :pub_date, :seq_update, :seq_original_list, :active, :drop_date, :drop_reason, :pes_number, :pes_version, :pes_listed, :needs_approval, :has_approval, :approval_info, :course_note, :extra_note, :extra_boolean, :extra_integer, :version_0, :version_a, :version_b, :version_c, :version_d, :version_e, :version_f, :version_g, :version_h, :version_i, :version_j, :version_k, :version_l, :version_m, :version_n)
    end

    def sort_column # inline header sort function
      params[:sort] || 'seq_number'
    end

    def sort_direction # inline header sort function
      params[:direction] || 'asc'
    end

end

app/helpers/datasheets_helper.rb
module DatasheetsHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title, :sort => column, :direction => direction
  end
end

app/views/datasheets/_form.html.erb
<%= form_with(model: datasheet, local: true) do |form| %>
  <% if datasheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(datasheet.errors.count, "error") %> prohibited this datasheet from being saved:</h2>

      <ul>
      <% datasheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :seq_number %>
    <%= form.number_field :seq_number, id: :datasheet_seq_number %>
  </div>

  <div class="field">
    <%= form.label :seq_version %>
    <%= form.text_field :seq_version, id: :datasheet_seq_version %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :datasheet_category %>
  </div>

  <div class="field">
    <%= form.label :seq_title %>
    <%= form.text_field :seq_title, id: :datasheet_seq_title %>
  </div>

  <div class="field">
    <%= form.label :hours %>
    <%= form.number_field :hours, id: :datasheet_hours %>
  </div>

  <div class="field">
    <%= form.label :pub_date %>
    <%= form.date_select :pub_date, id: :datasheet_pub_date %>
  </div>

  <div class="field">
    <%= form.label :seq_update %>
    <%= form.date_select :seq_update, id: :datasheet_seq_update %>
  </div>

  <div class="field">
    <%= form.label :seq_original_list %>
    <%= form.date_select :seq_original_list, id: :datasheet_seq_original_list %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :datasheet_active %>
  </div>

  <div class="field">
    <%= form.label :drop_date %>
    <%= form.date_select :drop_date, id: :datasheet_drop_date %>
  </div>

  <div class="field">
    <%= form.label :drop_reason %>
    <%= form.text_area :drop_reason, id: :datasheet_drop_reason %>
  </div>

  <div class="field">
    <%= form.label :pes_number, "PES Number" %>
    <!-- <p>Must enter '0' for courses with no PES number</p> -->
    <%= form.number_field :pes_number, id: :datasheet_pes_number, placeholder: 'Enter 0 if no PES #' %>
  </div>

  <div class="field">
    <%= form.label :pes_version, "PES Version" %>
    <%= form.text_field :pes_version, id: :datasheet_pes_version %>
  </div>

  <!-- <div class="field">
    <%= form.label :pes_listed, "PES Dropped Course - check if not listed by pes" %>
    <%= form.check_box :pes_listed, id: :datasheet_pes_listed %>
  </div> -->

  <div class="field">
    <%= form.label :needs_approval %>
    <%= form.check_box :needs_approval, id: :datasheet_needs_approval %>
  </div>

  <div class="field">
    <%= form.label :has_approval %>
    <%= form.check_box :has_approval, id: :datasheet_has_approval %>
  </div>

  <div class="field">
    <%= form.label :approval_info %>
    <%= form.text_area :approval_info, id: :datasheet_approval_info %>
  </div>

  <div class="field">
    <%= form.label :course_note %>
    <%= form.text_area :course_note, id: :datasheet_course_note %>
  </div>

  <div class="field">
    <%= form.label :extra_note %>
    <%= form.text_area :extra_note, id: :datasheet_extra_note %>
  </div>

  <!-- <div class="field">
    <%= form.label :extra_boolean %>
    <%= form.check_box :extra_boolean, id: :datasheet_extra_boolean %>
  </div>

  <div class="field">
    <%= form.label :extra_integer %>
    <%= form.number_field :extra_integer, id: :datasheet_extra_integer %>
  </div> -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/datasheets/index.html.erb
<p id="notice"><%= notice %></p>

<div class="well jumbotron text-center">
  <h1>Course Data</h1>
  <p>Details on all Sequoia courses</p>
</div>

<div class="row">
<div class="col-md-3">
  <input class="form-control" id="myInput" type="text" placeholder="Search Datasheet">
<br>
  <%= link_to 'Add New', new_datasheet_path, class: 'btn btn-primary' %>
  <%= link_to 'Export(csv)', datasheets_path('csv'), class: 'btn btn-default' %>
</div>
</div>
</br>

<h4>Active Courses: <%= @active_courses.length %></h4>
<h4>Active Ethics: <%= @active_courses_ethics.length %></h4>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Status</th>
      <th><%= sortable_mailing 'seq_number', 'Seq' %></th> <!--sortable column header -->
      <th>V</th>
      <th>Title</th>
      <th>Hours</th>
      <th>Category</th>
      <th><%= sortable 'pub_date', 'Pub date' %></th> <!--sortable column header -->
      <th>Update Date</th>
      <th>Org list Date</th>
      <!-- <th>Active</th> - became status at the top-->
      <!-- <th>Drop date</th> -->
      <!-- <th>Drop reason</th> -->
      <th>#</th>
      <th>V</th>
      <!-- <th>Pes listed</th> -->
      <th>Approvals</th>
      <!-- <th>Has approval</th> -->
      <!-- <th>Approval info</th> -->
      <th>Notes</th>
      <!-- <th>Extra note</th> -->
      <!-- <th>Extra boolean</th> -->
      <!-- <th>Extra integer</th> -->
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody id="myTable"> <!--myTable id is for search/filter js -->
    <% @datasheets.each do |datasheet| %>
      <tr>
        <% if datasheet.active == true %>
          <td class="green_text">Listed</td>
        <% elsif %>
          <td>Dropped</td>
        <% end %>
        <td><%= link_to datasheet.seq_number, datasheet %></td>
        <td><%= datasheet.seq_version %></td>
        <td><%= truncate(datasheet.seq_title, :length => 25) %></td>
        <td><%= datasheet.hours %></td>
        <td><%= truncate(datasheet.category, :length => 25) %></td>
        <td><%= datasheet.pub_date.blank? == false ? datasheet.pub_date.strftime('%-m/%-d/%y') : 'missing' %></td>
        <td><%= datasheet.seq_update.blank? == false && datasheet.seq_update.strftime('%-m/%-d/%y') == '1/1/13' ? 'unknown' : datasheet.seq_update.blank? == false ? datasheet.seq_update.strftime('%-m/%-d/%y') : 'missing' %></td>
        <td><%= datasheet.seq_original_list.blank? == false && datasheet.seq_original_list.strftime('%-m/%-d/%y') == '1/1/13' ? 'unknown' : datasheet.seq_original_list.blank? == false ? datasheet.seq_original_list.strftime('%-m/%-d/%y') : 'missing' %></td>
        <!-- <td><%= datasheet.seq_original_list %></td> -->
        <!-- <td><%= datasheet.active %></td> -->
        <!-- <td><%= datasheet.drop_date %></td> -->
        <!-- <td><%= datasheet.drop_reason %></td> -->
        <td><%= datasheet.pes_number %></td>
        <td><%= datasheet.pes_version %></td>
        <!-- <td><%= datasheet.pes_listed %></td> -->
        <!-- <td><%= datasheet.pes_listed ? 'Unlisted' : 'Listed' %></td> -->
        <!-- <td><%= datasheet.needs_approval %></td> -->
        <% if datasheet.needs_approval == true %>
          <td><%= link_to 'Details', datasheet %></td>
        <% elsif %>
          <td></td>
        <% end %>
        <!-- <td><%= datasheet.has_approval %></td> -->
        <!-- <td><%= datasheet.approval_info %></td> -->
        <td><%= datasheet.course_note %></td>
        <!-- <td><%= datasheet.extra_note %></td> -->
        <!-- <td><%= datasheet.extra_boolean %></td> -->
        <!-- <td><%= datasheet.extra_integer %></td> -->
        <td><%= link_to 'New Update', new_updatesheet_path(:datasheet_id => datasheet, :pes_number => datasheet.pes_number, :seq_version => datasheet.seq_version, :pes_version => datasheet.pes_version, :seq_number => datasheet.seq_number, :seq_title => datasheet.seq_title, :pub_date => datasheet.pub_date) %></td>
        <!-- <td><%= link_to 'View', datasheet %></td> -->
        <!-- <td><%= link_to 'Edit', edit_datasheet_path(datasheet) %></td> -->
        <td><%= link_to 'Delete', datasheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<h3>Upload CSV File</h3>
  <%= form_tag import_datasheets_path, multipart: true do %>
  <%= file_field_tag :file %>
</br>
  <%= submit_tag 'Upload', class: 'btn btn-primary' %>
<% end %>
</br>
<%= link_to "Remove All", remove_all_datasheets_path, :method => :get %>

app/views/datasheets/show.html.erb
<p id="notice"><%= notice %></p>

<!-- <div class="well jumbotron text-center">
  <h1>Course Details</h1>
  <p><%= @datasheet.seq_number %><%= @datasheet.seq_version %> - <%= @datasheet.seq_title %></p>
</div> -->
</br>
<div class="col-lg-offset-2 col-lg-8">
  <h3 class="text-center"><strong><%= @datasheet.seq_number %><%= @datasheet.seq_version %> - <%= @datasheet.seq_title %></strong></h3>
<%= link_to 'Back to Index', datasheets_path, class: 'btn btn-primary' %> <%= link_to 'Edit Course', edit_datasheet_path(@datasheet), class: 'btn btn-primary' %>
</br>
</br>
<div class="well well-white">
  <!-- <h2><strong>Course</strong></h2> -->
<!-- </br> -->

<% if @datasheet.active == true %>
  <h4 class="green"><strong>Active Course</strong></h4>
  <% elsif %>
  <h4 class="red"><strong>Inactive Course</strong></h4>
<% end %>
</br>
<div class="row">
<div class="col-lg-4">
<p>
  <strong>Number:</strong>
  <%= @datasheet.seq_number %>
</p>
<p>
  <strong>Current Version:</strong>
  <%= @datasheet.seq_version %>
</p>
<p>
  <strong>Title:</strong>
  <%= @datasheet.seq_title %>
</p>
<p>
  <strong>Category:</strong>
  <%= @datasheet.category %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @datasheet.hours %>
</p>
</div>
<div class="col-lg-4">

<p>
  <strong>PES Number:</strong>
  <%= @datasheet.pes_number != 0 ? @datasheet.pes_number : 'Not PES Course'%>
</p>

<p>
  <strong>PES Current Version:</strong>
  <%= @datasheet.pes_number != 0 ? @datasheet.pes_version : 'N/A'%>
</div>

<div class="col-lg-4">

<p>
  <strong>Publication Date:</strong>
  <%= @datasheet.pub_date.blank? == false ? @datasheet.pub_date.strftime('%-m/%-d/%y') : 'n/a' %>
</p>

<p>
  <strong>Sequoia Last Update:</strong>
  <%= @datasheet.seq_update.blank? == false && @datasheet.seq_update.strftime('%-m/%-d/%y') != '1/1/13' && @datasheet.seq_update.strftime('%-m/%-d/%y') != @datasheet.seq_original_list.strftime('%-m/%-d/%y') ? @datasheet.seq_update.strftime('%-m/%-d/%y') : 'N/A' %>
</p>

<p>
  <strong>Original listing Date:</strong>
  <%= @datasheet.seq_original_list.blank? == false && @datasheet.seq_original_list.strftime('%-m/%-d/%y') != '1/1/13' ? @datasheet.seq_original_list.strftime('%-m/%-d/%y') : 'N/A' %>
</p>

</div>
</div>
</br>
</br>
<p>
  <strong>Addtional Course Note:</strong>
  <%= @datasheet.course_note.blank? == false ? @datasheet.course_note : 'N/A'%>
</p>
</br>

<% if @datasheet.active == false %>
  <div class="well ">
</br>
    <p>
      <strong>Date Dropped:</strong>
      <%= @datasheet.drop_date.blank? == false ? @datasheet.drop_date.strftime('%-m/%-d/%y') : 'n/a' %>
    </p>

    <p>
      <strong>Reason Course Was Dropped:</strong>
      <%= @datasheet.drop_reason.blank? == false ? @datasheet.drop_reason : 'N/A' %>
    </p>
  </div>
<% end %>

<% if @datasheet.needs_approval == true %>
  <div class="well well-white ">
  <h4><strong>Course Needs Specific aproval</strong></h4>
    <p>
      <!-- <strong>Has Approval:</strong> -->
      <%= @datasheet.has_approval == true ? 'Has Approval' : 'Does not have approval' %>
    </p>
    <p>
      <!-- <strong>Reason Course Was Dropped:</strong> -->
      <%= @datasheet.approval_info %>
    </p>
  </div>
  </br>
<% end %>
</br>

<div class="row">
  <div class="well well-white col-lg-10 col-lg-offset-1">
  <h3 class="text-center">Older Version Publication Dates</h3>
  <h4 class="text-center">Average Time Between Publications: <strong><%= @time_between.blank? == false ? "#{@time_between} Days" : 'n/a' %> </strong></h4>
  <div class="col-lg-4">
    <p><%= @datasheet.version_a.blank? == false && @datasheet.seq_version > 'A' ? "Version A: #{@datasheet.version_a.strftime('%-m/%-d/%y')}" : '' %></p>
    <p><%= @datasheet.version_b.blank? == false && @datasheet.seq_version > 'B' ? "Version B: #{@datasheet.version_b.strftime('%-m/%-d/%y')}" : ''  %></p>
    <p><%= @datasheet.version_c.blank? == false && @datasheet.seq_version > 'C' ? "Version C: #{@datasheet.version_c.strftime('%-m/%-d/%y')}" : '' %></p>
    <p><%= @datasheet.version_d.blank? == false && @datasheet.seq_version > 'D' ? "Version D: #{@datasheet.version_d.strftime('%-m/%-d/%y')}" : '' %></p>
    <p><%= @datasheet.version_e.blank? == false && @datasheet.seq_version > 'E' ? "Version E: #{@datasheet.version_e.strftime('%-m/%-d/%y')}" : '' %></p>
  </div>
  <div class="col-lg-4">
    <p><%= @datasheet.version_f.blank? == false && @datasheet.seq_version > 'F' ? "Version F: #{@datasheet.version_f.strftime('%-m/%-d/%y')}" : ''  %></p>
    <p><%= @datasheet.version_g.blank? == false && @datasheet.seq_version > 'G' ? "Version G: #{@datasheet.version_g.strftime('%-m/%-d/%y')}" : '' %></p>
    <p><%= @datasheet.version_h.blank? == false && @datasheet.seq_version > 'H' ? "Version H: #{@datasheet.version_H.strftime('%-m/%-d/%y')}" : '' %></p>
    <p><%= @datasheet.version_i.blank? == false && @datasheet.seq_version > 'I' ? "Version I: #{@datasheet.version_i.strftime('%-m/%-d/%y')}" : '' %></p>
    <p><%= @datasheet.version_j.blank? == false && @datasheet.seq_version > 'J' ? "Version J: #{@datasheet.version_j.strftime('%-m/%-d/%y')}" : ''  %></p>
  </div>
  <div class="col-lg-4">
    <p><%= @datasheet.version_k.blank? == false && @datasheet.seq_version > 'K' ? "Version K: #{@datasheet.version_k.strftime('%-m/%-d/%y')}" : '' %></p>
    <p><%= @datasheet.version_l.blank? == false && @datasheet.seq_version > 'L' ? "Version L: #{@datasheet.version_l.strftime('%-m/%-d/%y')}" : '' %></p>
    <p><%= @datasheet.version_m.blank? == false && @datasheet.seq_version > 'M' ? "Version M: #{@datasheet.version_m.strftime('%-m/%-d/%y')}" : '' %></p>
    <p><%= @datasheet.version_n.blank? == false && @datasheet.seq_version > 'N' ? "Version N: #{@datasheet.version_n.strftime('%-m/%-d/%y')}" : '' %></p>
  </div>
</div>
</div>

</div> <!--Well end -->