config/routes.rb
Rails.application.routes.draw do

  resources :empire_master_no_matches do
    collection {post :import}
  end
  resources :empire_master_matches do
    collection {post :import}
  end
  resources :master_ea_double_accounts do
    collection {post :import}
  end
  resources :master_cpa_double_accounts do
    collection {post :import}
  end
  resources :master_ea_no_matches do
    collection {post :import}
  end
  resources :master_ea_matches do
    collection {post :import}
  end
  resources :master_eas do
    collection {post :import}
    collection do
      get 'search'
      get 'no_mail_ea'
      get 'ea_customers'
    end
  end
  resources :master_cpa_matches do
    collection {post :import}
  end
  resources :master_cpa_no_matches do
    collection {post :import}
  end
  resources :master_cpas do
    collection {post :import}
    collection do
      get 'search'
      get 'no_mail_cpa'
      get 'cpa_customers'
    end
  end
  resources :empire_rc_states do
    collection {
      get 'upload_list'
    }
  end
  resources :email_records
  resources :email_exports
  resources :quotes
  resources :sequoia_customer_matches
  resources :postcard_records
  resources :postcard_exports

  resources :empire_master_lists do
    collection {post :import}
    collection do
      get 'ny'
      get 'ny_marketing'
      get 'ny_week'
    end
  end
  resources :empire_state_lists
  resources :s_customers do
    collection {post :import}
    collection do
      get 'data'
      get 'rc_marketing'
      get 'sales'
    end
  end
  resources :empire_customers do
    collection {post :import}
    collection do
      get 'exports'
      get 'sales'
      get 'rc_marketing'
      get 'b_exp'
      get 'rolling_email_export'
    end
  end

  resources :master_lists do
    collection {post :import}
    collection do
      get 'remove_all'
      get 'no_mail_add'
      get 'no_mail'
      get 'mailings'
    end
  end

  resources :mailing_empire_nms do
    collection {post :import}
    collection do
      get 'remove_all'
      get 'no_mail'
      get 'data'
    end
  end

  resources :sales do
    collection {post :import}
  end
  resources :task_deadlines
  resources :course_creation_tasks
  resources :empire_courses
  resources :course_creation_templetes
  resources :calendars
  resources :live_chat_answers
  resources :cpe_due_dates do
    collection {post :import}
    end

  resources :course_comments
  resources :call_logs do
    collection do
      get 'add_new_select_topic'
    end
  end
  resources :seq_no_mails do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end
  # get 'exam_results/index'
  # get 'exam_results/import' => 'exam_results#my_import'
  resources :exam_results do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end
  get 'exam_results/index0'
  resources :email_campaigns
  resources :inventories
  resources :postcard_mailings
  resources :tx_royalties
  resources :empire_mailings
  resources :mailings do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end
  resources :tasks
  # resources :sequoia_customers
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'sequoia/dash'
  get 'sequoia/dash_ashley'
  get 'sequoia/dash_michael'
  get 'sequoia/dash_sabrina'
  get 'sequoia/dash_kyle'
  get 'sequoia/dash_john'
  get 'sequoia/dash_christian'
  get 'sequoia/dash_james'
  get 'sequoia/dash_extra'
  get 'sequoia/s_data'

  resources :date_fields
  resources :pes_courses do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end

  resources :postcard_returns
  get 'sales_report/postcard_return_stats'
  get 'sales_report/call_log_stats'
  get 'sales_report/sequoia_sales'
  get 'sales_report/sequoia_exams'

  get 'test_pages/test_1'

  get 'sales_report/course_status'
  get 'sequoia_customers/index'

  get 'sequoia_customers/import' => 'sequoia_customers#my_import'
  resources :sequoia_customers do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end

  get 'sequoia_exams/import' => 'sequoia_exams#my_import'
  resources :sequoia_exams do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end

  get 'empire/dash'

  get 'empire/dash'
  resources :copyrights
  devise_for :users
  # get 'updatesheets/:id/', to: redirect("/updatesheets")
  resources :updatesheets
  resources :datasheets do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end

  root :to => 'home#index'

  # user_signed_in? && current_user.email == 'austin@sequoiacpe.com' ? root :to => "sequoia#dash" : ''
  # user_signed_in? && current_user.email == 'ashley@sequoiacpe.com' ? root :to => "sequoia#dash_ashley" : ''
  # user_signed_in? && current_user.email == 'kyle@sequoiacpe.com' ? root :to => "datasheets#index" : ''
  # user_signed_in? && current_user.email == 'micheal@sequoiacpe.com' ? root :to => "datasheets#index" : ''
  # root :to => "datasheets#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/master_ea_no_match.rb
class MasterEaNoMatch < ApplicationRecord

  def self.my_import(file)
    batch,batch_size = [], 2_000
    CSV.foreach(file.path, headers: true, header_converters: :symbol, :encoding => 'utf-8') do |row|
      batch << MasterEaNoMatch.new(row.to_hash)
      if batch.size >= batch_size
        MasterEaNoMatch.import batch
          batch = []
    end
  end
    MasterEaNoMatch.import batch
  end

  def self.to_csv # Export to csv function
    attributes = %w{list uid lname search_date}
    CSV.generate(headers: true) do |csv|
      csv << attributes

        all.each do |master_ea_match|
          csv << attributes.map{ |attr| master_ea_match.send(attr) }
        end
    end
  end
end

app/controllers/master_ea_no_matches_controller.rb
class MasterEaNoMatchesController < ApplicationController
  before_action :set_master_ea_no_match, only: [:show, :edit, :update, :destroy]

  # GET /master_ea_no_matches
  # GET /master_ea_no_matches.json
  def index
    @master_ea_no_matches = MasterEaNoMatch.all

    # Remove All
    if params['remove_all'] == 'yes' && params['confirm'] == 'yes'
      MasterEaNoMatch.delete_all
      redirect_to master_ea_no_matches_path(), note: 'Records Deleted'
    end

    respond_to do |format|
      format.html
      format.csv { send_data @master_ea_no_matches.to_csv, filename: "Sequoia-no-matched-customers-ea-#{Date.today}.csv" }
    end

    if params['no_match'] == 'yes'
      uid = params['uid'].to_i
      lname = SCustomer.where(uid: uid).pluck(:lname)
      list_1 = MasterEa.first(1)
      list = list_1.pluck(:list)
      new = MasterEaNoMatch.create(
      uid: uid,
      lname: lname[0],
      list: list[0],
      search_date: Date.today,
      )
      new.save
      redirect_to master_eas_path(), notice: "UID #{uid} was added to 'No Match' table"
    end

  end

  # GET /master_ea_no_matches/1
  # GET /master_ea_no_matches/1.json
  def show
  end

  # GET /master_ea_no_matches/new
  def new
    @master_ea_no_match = MasterEaNoMatch.new
  end

  # GET /master_ea_no_matches/1/edit
  def edit
  end

  # POST /master_ea_no_matches
  # POST /master_ea_no_matches.json
  def create
    @master_ea_no_match = MasterEaNoMatch.new(master_ea_no_match_params)

    respond_to do |format|
      if @master_ea_no_match.save
        format.html { redirect_to @master_ea_no_match, notice: 'Master ea no match was successfully created.' }
        format.json { render :show, status: :created, location: @master_ea_no_match }
      else
        format.html { render :new }
        format.json { render json: @master_ea_no_match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /master_ea_no_matches/1
  # PATCH/PUT /master_ea_no_matches/1.json
  def update
    respond_to do |format|
      if @master_ea_no_match.update(master_ea_no_match_params)
        format.html { redirect_to @master_ea_no_match, notice: 'Master ea no match was successfully updated.' }
        format.json { render :show, status: :ok, location: @master_ea_no_match }
      else
        format.html { render :edit }
        format.json { render json: @master_ea_no_match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /master_ea_no_matches/1
  # DELETE /master_ea_no_matches/1.json
  def destroy
    @master_ea_no_match.destroy
    respond_to do |format|
      format.html { redirect_to master_ea_no_matches_url, notice: 'Master ea no match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import #Uploading CSV function
    MasterEaNoMatch.my_import(params[:file])
    redirect_to master_ea_no_matches_path, notice: "Upload Complete"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_master_ea_no_match
      @master_ea_no_match = MasterEaNoMatch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def master_ea_no_match_params
      params.require(:master_ea_no_match).permit(:uid, :lname, :list, :search_date)
    end
end

app/helpers/master_ea_no_matches_helper.rb
module MasterEaNoMatchesHelper
end

app/views/master_ea_no_matches/_form.html.erb
<%= simple_form_for(@master_ea_no_match) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :uid %>
    <%= f.input :lname %>
    <%= f.input :list %>
    <%= f.input :search_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/master_ea_no_matches/edit.html.erb
<h1>Editing Master Ea No Match</h1>

<%= render 'form', master_ea_no_match: @master_ea_no_match %>

<%= link_to 'Show', @master_ea_no_match %> |
<%= link_to 'Back', master_ea_no_matches_path %>

app/views/master_ea_no_matches/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="well col-md-3">
    <p>Upload New EA No Match List (CSV)</p>
      <%= form_tag import_master_ea_no_matches_path, multipart: true do %>
      <%= file_field_tag :file %>
    <br>
      <%= submit_tag 'Upload', class: 'btn btn-default' %>
    <% end %>
  <br>
    <% if params['remove_all'] == 'yes' %>
      <p><%= link_to "Confirm Delete", master_ea_no_matches_path(remove_all: 'yes', confirm: 'yes') %></p>
    <% else %>
      <p><%= link_to "Remove All Records", master_ea_no_matches_path(remove_all: 'yes') %></p>
    <% end %>
  </div>
</div>

<h1 class="text-center">Master EA No Matches</h1>
<p class="text-center"><%= link_to 'Back to EA search', ea_customers_master_eas_path() %></p>
<p><%= link_to 'Export', master_ea_no_matches_path('csv'), class: 'btn btn-primary' %></p>


<table class="table table-outline">
  <caption>Displaying <%= number_with_delimiter(MasterEaNoMatch.limit(500).count) %> of <%= number_with_delimiter(MasterEaNoMatch.count) %></caption>
  <thead>
    <tr>
      <th>Uid</th>
      <th>Lname</th>
      <th>List</th>
      <th>Search date</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @master_ea_no_matches.order(created_at: :DESC).limit(500).each do |master_ea_no_match| %>
      <tr>
        <td><%= master_ea_no_match.uid %></td>
        <td><%= master_ea_no_match.lname %></td>
        <td><%= master_ea_no_match.list %></td>
        <td><%= master_ea_no_match.search_date %></td>
        <td><%= link_to 'Destroy', master_ea_no_match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Master Ea No Match', new_master_ea_no_match_path %>

app/views/master_ea_no_matches/new.html.erb
<h1>New Master Ea No Match</h1>

<%= render 'form', master_ea_no_match: @master_ea_no_match %>

<%= link_to 'Back', master_ea_no_matches_path %>

app/views/master_ea_no_matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uid:</strong>
  <%= @master_ea_no_match.uid %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @master_ea_no_match.lname %>
</p>

<p>
  <strong>List:</strong>
  <%= @master_ea_no_match.list %>
</p>

<p>
  <strong>Search date:</strong>
  <%= @master_ea_no_match.search_date %>
</p>

<%= link_to 'Edit', edit_master_ea_no_match_path(@master_ea_no_match) %> |
<%= link_to 'Back', master_ea_no_matches_path %>