config/routes.rb
Rails.application.routes.draw do

  resources :empire_master_no_matches do
    collection {post :import}
  end
  resources :empire_master_matches do
    collection {post :import}
  end
  resources :master_ea_double_accounts do
    collection {post :import}
  end
  resources :master_cpa_double_accounts do
    collection {post :import}
  end
  resources :master_ea_no_matches do
    collection {post :import}
  end
  resources :master_ea_matches do
    collection {post :import}
  end
  resources :master_eas do
    collection {post :import}
    collection do
      get 'search'
      get 'no_mail_ea'
      get 'ea_customers'
    end
  end
  resources :master_cpa_matches do
    collection {post :import}
  end
  resources :master_cpa_no_matches do
    collection {post :import}
  end
  resources :master_cpas do
    collection {post :import}
    collection do
      get 'search'
      get 'no_mail_cpa'
      get 'cpa_customers'
    end
  end
  resources :empire_rc_states do
    collection {
      get 'upload_list'
    }
  end
  resources :email_records
  resources :email_exports
  resources :quotes
  resources :sequoia_customer_matches
  resources :postcard_records
  resources :postcard_exports

  resources :empire_master_lists do
    collection {post :import}
    collection do
      get 'ny'
      get 'ny_marketing'
      get 'ny_week'
    end
  end
  resources :empire_state_lists
  resources :s_customers do
    collection {post :import}
    collection do
      get 'data'
      get 'rc_marketing'
      get 'sales'
    end
  end
  resources :empire_customers do
    collection {post :import}
    collection do
      get 'exports'
      get 'sales'
      get 'rc_marketing'
      get 'b_exp'
      get 'rolling_email_export'
    end
  end

  resources :master_lists do
    collection {post :import}
    collection do
      get 'remove_all'
      get 'no_mail_add'
      get 'no_mail'
      get 'mailings'
    end
  end

  resources :mailing_empire_nms do
    collection {post :import}
    collection do
      get 'remove_all'
      get 'no_mail'
      get 'data'
    end
  end

  resources :sales do
    collection {post :import}
  end
  resources :task_deadlines
  resources :course_creation_tasks
  resources :empire_courses
  resources :course_creation_templetes
  resources :calendars
  resources :live_chat_answers
  resources :cpe_due_dates do
    collection {post :import}
    end

  resources :course_comments
  resources :call_logs do
    collection do
      get 'add_new_select_topic'
    end
  end
  resources :seq_no_mails do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end
  # get 'exam_results/index'
  # get 'exam_results/import' => 'exam_results#my_import'
  resources :exam_results do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end
  get 'exam_results/index0'
  resources :email_campaigns
  resources :inventories
  resources :postcard_mailings
  resources :tx_royalties
  resources :empire_mailings
  resources :mailings do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end
  resources :tasks
  # resources :sequoia_customers
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'sequoia/dash'
  get 'sequoia/dash_ashley'
  get 'sequoia/dash_michael'
  get 'sequoia/dash_sabrina'
  get 'sequoia/dash_kyle'
  get 'sequoia/dash_john'
  get 'sequoia/dash_christian'
  get 'sequoia/dash_james'
  get 'sequoia/dash_extra'
  get 'sequoia/s_data'

  resources :date_fields
  resources :pes_courses do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end

  resources :postcard_returns
  get 'sales_report/postcard_return_stats'
  get 'sales_report/call_log_stats'
  get 'sales_report/sequoia_sales'
  get 'sales_report/sequoia_exams'

  get 'test_pages/test_1'

  get 'sales_report/course_status'
  get 'sequoia_customers/index'

  get 'sequoia_customers/import' => 'sequoia_customers#my_import'
  resources :sequoia_customers do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end

  get 'sequoia_exams/import' => 'sequoia_exams#my_import'
  resources :sequoia_exams do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end

  get 'empire/dash'

  get 'empire/dash'
  resources :copyrights
  devise_for :users
  # get 'updatesheets/:id/', to: redirect("/updatesheets")
  resources :updatesheets
  resources :datasheets do
    collection {post :import}
    collection do
      get 'remove_all'
    end
  end

  root :to => 'home#index'

  # user_signed_in? && current_user.email == 'austin@sequoiacpe.com' ? root :to => "sequoia#dash" : ''
  # user_signed_in? && current_user.email == 'ashley@sequoiacpe.com' ? root :to => "sequoia#dash_ashley" : ''
  # user_signed_in? && current_user.email == 'kyle@sequoiacpe.com' ? root :to => "datasheets#index" : ''
  # user_signed_in? && current_user.email == 'micheal@sequoiacpe.com' ? root :to => "datasheets#index" : ''
  # root :to => "datasheets#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
class Sale < ApplicationRecord

  require 'csv'
  require 'activerecord-import/base'
  require 'activerecord-import/active_record/adapters/postgresql_adapter'

  def self.to_csv # Export to csv function
    attributes = %w{day sequoia empire pacific}
    CSV.generate(headers: true) do |csv|
      csv << attributes

        all.each do |sale|
          csv << attributes.map{ |attr| sale.send(attr) }
        end
    end
  end

  def self.my_import(file)
    batch,batch_size = [], 1_000
    CSV.foreach(file.path, headers: true, header_converters: :symbol, :encoding => 'utf-8') do |row|
      batch << Sale.new(row.to_hash)
      if batch.size >= batch_size
        Sale.import batch
          batch = []
    end
  end
    Sale.import batch
  end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
    @sales_display = Sale.order('day DESC').all
    @sales_enter = Sale.order('day ASC').all

    @week_b = Date.today.at_beginning_of_week - 64.days
    @week_e = Date.today.at_end_of_week
    @dates = Sale.where('day > ?', @week_b).where('day < ?', @week_e + 1.day).order('day ASC').pluck(:day)


    @sales_seq = Sale.where('day > ?', @week_b).where('day < ?', @week_e + 1.day).order('day ASC').all
    # @sales_seq = Sale.where('day > ?', @week_b).where('day < ?', @week_e + 1.day).order('day ASC').pluck(:sequoia)
    @test = Sale.where('day > ?', @week_b).where('day < ?', @week_e + 1.day).order('day ASC').pluck(:day)

    #DAYS of the WEEK
    @mon = []
    @tue = []
    @wed = []
    @thu = []
    @fri = []
    @sat = []
    @sun = []
    @sales_seq.each do |i|
      i.day.wday == 1 ? @mon.push(i.sequoia) : ''
      i.day.wday == 2 ? @tue.push(i.sequoia) : ''
      i.day.wday == 3 ? @wed.push(i.sequoia) : ''
      i.day.wday == 4 ? @thu.push(i.sequoia) : ''
      i.day.wday == 5 ? @fri.push(i.sequoia) : ''
      i.day.wday == 6 ? @sat.push(i.sequoia) : ''
      i.day.wday == 0 ? @sun.push(i.sequoia) : ''
    end

# EXPORT
    respond_to do |format|
      format.html
      format.csv { send_data @sales.to_csv, filename: "sales-#{Date.today}.csv" }
    end
#EXPORT
year_change
table_2
  end

  def year_change
    @week_b_year = (Date.today.at_beginning_of_week - 64.days)
    @week_e_year = (Date.today.at_end_of_week)
    @sales_seq_year = Sale.where('day > ?', @week_b_year).where('day < ?', @week_e_year + 1.day).order('day ASC').all

    @weeks = []
    @sales_seq_year.each do |i|
      @weeks.push(i.sequoia)
    end
  end

  def table_2

    @week_b_2 = (((Date.today - 128.days).at_beginning_of_week) - 1.day)
    @week_e_2 = (((Date.today - 67.days).at_end_of_week) + 1.day)
    @dates_2 = Sale.where('day > ?', @week_b_2).where('day < ?', @week_e_2).order('day ASC').pluck(:day)


    @sales_seq_2 = Sale.where('day > ?', @week_b_2).where('day < ?', @week_e_2).order('day ASC').all
    # @sales_seq = Sale.where('day > ?', @week_b).where('day < ?', @week_e + 1.day).order('day ASC').pluck(:sequoia)
    # @test = Sale.where('day > ?', @week_b).where('day < ?', @week_e + 1.day).order('day ASC').pluck(:day)

    #DAYS of the WEEK
    @mon_2 = []
    @tue_2 = []
    @wed_2 = []
    @thu_2 = []
    @fri_2 = []
    @sat_2 = []
    @sun_2 = []
    @sales_seq_2.each do |i|
      i.day.wday == 1 ? @mon_2.push(i.sequoia) : ''
      i.day.wday == 2 ? @tue_2.push(i.sequoia) : ''
      i.day.wday == 3 ? @wed_2.push(i.sequoia) : ''
      i.day.wday == 4 ? @thu_2.push(i.sequoia) : ''
      i.day.wday == 5 ? @fri_2.push(i.sequoia) : ''
      i.day.wday == 6 ? @sat_2.push(i.sequoia) : ''
      i.day.wday == 0 ? @sun_2.push(i.sequoia) : ''
    end

  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to sequoia_dash_path, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import #Uploading CSV function
    Sale.my_import(params[:file])
    redirect_to sales_path, notice: "Upload Complete"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:day, :sequoia, :empire, :pacific, :extra_d, :extra_s, :extra_b)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= simple_form_for(@sale) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :day %>
    <div class="row">
      <div class="col-lg-4">
        <%= f.input :sequoia %>
      </div>
      <div class="col-lg-4">
        <%= f.input :empire %>
      </div>
      <div class="col-lg-4">
        <%= f.input :pacific %>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/sales/_week_table_2.html.erb
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th></th>
      <th colspan="10" class="text-center">Sequoia</th>
    </tr>
    <tr>
      <th></th>
      <% @dates_2.each do |i| %>
        <% if i.strftime('%a') == 'Mon' %>
          <th><%= i.strftime('%-m/%-d/%y') %></th>
        <% end %>
      <% end %>
    </tr>
  </thead>
  <tr>
    <td>Monday</td>
    <% @mon_2.each do |i| %>
      <td><%= number_to_currency(i) %></td>
    <% end %>
  </tr>
  <tr>
    <td>Tuesday</td>
    <% @tue_2.each do |i| %>
      <td><%= number_to_currency(i) %></td>
    <% end %>
  </tr>
  <tr>
    <td>Wednesday</td>
    <% @wed_2.each do |i| %>
      <td><%= number_to_currency(i) %></td>
    <% end %>
  </tr>
  <tr>
    <td>Thursday</td>
    <% @thu_2.each do |i| %>
      <td><%= number_to_currency(i) %></td>
    <% end %>
  </tr>
  <tr>
    <td>Friday</td>
    <% @fri_2.each do |i| %>
      <td><%= number_to_currency(i) %></td>
    <% end %>
  </tr>
  <tr>
    <td>Saturday</td>
    <% @sat_2.each do |i| %>
      <td><%= number_to_currency(i) %></td>
    <% end %>
  </tr>
  <tr>
    <td>Sunday</td>
    <% @sun_2.each do |i| %>
      <td><%= number_to_currency(i) %></td>
    <% end %>
  </tr>
  <tr>
    <td><strong>Total</strong></td>
    <td><strong><%= number_to_currency(@mon_2[0] + @tue_2[0] + @wed_2[0] + @thu_2[0] + @fri_2[0] + @sat_2[0] + @sun_2[0]) %></strong></td>
    <td><strong><%= number_to_currency(@mon_2[1] + @tue_2[1] + @wed_2[1] + @thu_2[1] + @fri_2[1] + @sat_2[1] + @sun_2[1]) %></strong></td>
    <td><strong><%= number_to_currency(@mon_2[2] + @tue_2[2] + @wed_2[2] + @thu_2[2] + @fri_2[2] + @sat_2[2] + @sun_2[2]) %></strong></td>
    <td><strong><%= number_to_currency(@mon_2[3] + @tue_2[3] + @wed_2[3] + @thu_2[3] + @fri_2[3] + @sat_2[3] + @sun_2[3]) %></strong></td>
    <td><strong><%= number_to_currency(@mon_2[4] + @tue_2[4] + @wed_2[4] + @thu_2[4] + @fri_2[4] + @sat_2[4] + @sun_2[4]) %></strong></td>
    <td><strong><%= number_to_currency(@mon_2[5] + @tue_2[5] + @wed_2[5] + @thu_2[5] + @fri_2[5] + @sat_2[5] + @sun_2[5]) %></strong></td>
    <td><strong><%= number_to_currency(@mon_2[6] + @tue_2[6] + @wed_2[6] + @thu_2[6] + @fri_2[6] + @sat_2[6] + @sun_2[6]) %></strong></td>
    <td><strong><%= number_to_currency(@mon_2[7] + @tue_2[7] + @wed_2[7] + @thu_2[7] + @fri_2[7] + @sat_2[7] + @sun_2[7]) %></strong></td>
    <td><strong><%= number_to_currency(@mon_2[8] + @tue_2[8] + @wed_2[8] + @thu_2[8] + @fri_2[8] + @sat_2[8] + @sun_2[8]) %></strong></td>
    <td><strong><%= number_to_currency(@mon_2[9] + @tue_2[9] + @wed_2[9] + @thu_2[9] + @fri_2[9] + @sat_2[9] + @sun_2[9]) %></strong></td>
  </tr>
</table>

app/views/sales/_week_table_test.html.erb
<% @days = ['Monday','Tuesday','Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] %>
<table class="table">

    <% @days.each do |i| %><tr><td><%= i %></td></tr><% end %>
    <tr>
      <% @weeks.select { |x| @weeks.index(x) % 7 == 0}.each do |i| %><td><%= number_to_currency(i) %></td><% end %>
    </tr>
    <tr>
      <% @weeks.select { |x| @weeks.index(x) % 7 == 0}.each do |i| %><td><%= number_to_currency(i) %></td><% end %>
    </tr>
</table>


<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th></th>
      <th colspan="10" class="text-center">Sequoia</th>
    </tr>
    <tr>
      <th></th>
      <% @dates_2.each do |i| %>
        <% if i.strftime('%a') == 'Mon' %>
          <th><%= i.strftime('%-m/%-d/%y') %></th>
        <% end %>
      <% end %>
    </tr>
  </thead>
  <tr>
    <td>Monday</td>
    <% @weeks.select { |x| (@weeks.index(x) + 7) % 7 == 0}.each do |i| %>
      <td><%= number_to_currency(i) %></td>
    <% end %>
  </tr>
  <tr>
    <td>Tuesday</td>
    <% @weeks.select { |x| (@weeks.index(x) + 7) % 8 == 0}.each do |i| %>
      <td><%= number_to_currency(i) %></td>
    <% end %>
  </tr>
  <tr>
    <td>Wednesday</td>
    <% @weeks.select { |x| (@weeks.index(x) + 7) % 9 == 0}.each do |i| %>
      <td><%= number_to_currency(i) %></td>
    <% end %>
  </tr>
  <tr>
    <td>Thursday</td>
    <% @weeks.select { |x| (@weeks.index(x) + 7) % 10 == 0}.each do |i| %>
      <td><%= number_to_currency(i) %></td>
    <% end %>
  </tr>
  <tr>
    <td>Friday</td>
    <% @weeks.select { |x| (@weeks.index(x) + 7) % 11 == 0}.each do |i| %>
      <td><%= number_to_currency(i) %></td>
    <% end %>
  </tr>
  <tr>
    <td>Saturday</td>
    <% @sat_2.each do |i| %>
      <td><%= number_to_currency(i) %></td>
    <% end %>
  </tr>
  <tr>
    <td>Sunday</td>
    <% @sun_2.each do |i| %>
      <td><%= number_to_currency(i) %></td>
    <% end %>
  </tr>
</table>

app/views/sales/edit.html.erb
<h1 class="text-center">Editing Day Sales</h1>

<h2 class="text-center"><%= @sale.day.strftime('%a, %-m/%-d/%Y') %></h2>
</br>
<div class="well well-white col-lg-6 col-lg-offset-3">
  <%= render 'form', sale: @sale %>
</br>
  <%= link_to 'Show', @sale %> |
  <%= link_to 'Back', sales_path %>
</div>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Upload CSV File</h3>
  <%= form_tag import_sales_path, multipart: true do %>
  <%= file_field_tag :file %>
</br>
    <%= submit_tag 'Upload', class: 'btn btn-primary' %>
  <% end %>
</br>




<%= link_to 'Export', sales_path('csv'), class: 'btn btn-default' %>

<% if params['weekly'] == 'yes' %>
  <% @weekly = 'active' %>
<% elsif %>
  <% @weekly = '' %>
<% end %>
<% if params['weekly'] == 'yes' %>
  <% @home = '' %>
<% elsif %>
  <% @home = 'active' %>
<% end %>


<h1 class="text-center">Sales</h1>

<ul class="nav nav-tabs">
  <li class="<%= @home %>"><a data-toggle="tab" href="#home">Home</a></li>
  <li class= "<%= @weekly %>" ><a data-toggle="tab" href="#weekly">Weekly</a></li>
</ul>

<div class="tab-content">
  <div id="home" class="tab-pane fade in <%= @home %>">

  <div class="row">
    <div class="col-lg-6">


    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Day</th>
          <th>Sequoia</th>
          <th>Empire</th>
          <th>Pacific</th>
        </tr>
      </thead>

      <tbody>
        <% @sales_display.each do |sale| %>
        <% unless sale.sequoia == 0 && sale.empire == 0 %>
          <tr>
            <td><%= link_to sale.day.strftime('%a, %-m/%-d/%y'), edit_sale_path(sale) %></td>
            <td><%= sale.sequoia.blank? ? 0 : number_to_currency(sale.sequoia) %></td>
            <td><%= sale.empire.blank? ? 0 : number_to_currency(sale.empire) %></td>
            <td><%= sale.pacific.blank? ? 0 : number_to_currency(sale.pacific) %></td>
          </tr>
        <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-lg-6">



    <table class="table table-bordered well">
      <thead>
        <tr>
          <th>Day</th>
          <th>Sequoia</th>
          <th>Empire</th>
          <th>Pacific</th>
        </tr>
      </thead>

      <tbody>
        <% @sales_enter.each do |sale| %>
        <% if sale.sequoia == 0 && sale.empire == 0 %>
          <tr>
            <td><%= link_to sale.day.strftime('%a, %-m/%-d/%y'), edit_sale_path(sale) %></td>
            <td><%= sale.sequoia.blank? ? 0 : number_to_currency(sale.sequoia) %></td>
            <td><%= sale.empire.blank? ? 0 : number_to_currency(sale.empire) %></td>
            <td><%= sale.pacific.blank? ? 0 : number_to_currency(sale.pacific) %></td>
            <!-- <td><%= link_to 'Show', sale %></td>
            <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
            <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
          </tr>
        <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

</div>

  <div id="weekly" class="tab-pane fade in <%= @weekly %>">

    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th></th>
          <th colspan="10" class="text-center">Sequoia</th>
        </tr>
        <tr>
          <th></th>
          <% @dates.each do |i| %>
            <% if i.strftime('%a') == 'Mon' %>
              <th><%= i.strftime('%-m/%-d/%y') %></th>
            <% end %>
          <% end %>
        </tr>
      </thead>
      <tr>
        <td>Monday</td>
        <% @mon.each do |i| %>
          <td><%= number_to_currency(i) %></td>
        <% end %>
      </tr>
      <tr>
        <td>Tuesday</td>
        <% @tue.each do |i| %>
          <td><%= number_to_currency(i) %></td>
        <% end %>
      </tr>
      <tr>
        <td>Wednesday</td>
        <% @wed.each do |i| %>
          <td><%= number_to_currency(i) %></td>
        <% end %>
      </tr>
      <tr>
        <td>Thursday</td>
        <% @thu.each do |i| %>
          <td><%= number_to_currency(i) %></td>
        <% end %>
      </tr>
      <tr>
        <td>Friday</td>
        <% @fri.each do |i| %>
          <td><%= number_to_currency(i) %></td>
        <% end %>
      </tr>
      <tr>
        <td>Saturday</td>
        <% @sat.each do |i| %>
          <td><%= number_to_currency(i) %></td>
        <% end %>
      </tr>
      <tr>
        <td>Sunday</td>
        <% @sun.each do |i| %>
          <td><%= number_to_currency(i) %></td>
        <% end %>
      </tr>
      <tr>
        <td><strong>Total</strong></td>
        <td><strong><%= number_to_currency(@mon[0] + @tue[0] + @wed[0] + @thu[0] + @fri[0] + @sat[0] + @sun[0]) %></strong></td>
        <td><strong><%= number_to_currency(@mon[1] + @tue[1] + @wed[1] + @thu[1] + @fri[1] + @sat[1] + @sun[1]) %></strong></td>
        <td><strong><%= number_to_currency(@mon[2] + @tue[2] + @wed[2] + @thu[2] + @fri[2] + @sat[2] + @sun[2]) %></strong></td>
        <td><strong><%= number_to_currency(@mon[3] + @tue[3] + @wed[3] + @thu[3] + @fri[3] + @sat[3] + @sun[3]) %></strong></td>
        <td><strong><%= number_to_currency(@mon[4] + @tue[4] + @wed[4] + @thu[4] + @fri[4] + @sat[4] + @sun[4]) %></strong></td>
        <td><strong><%= number_to_currency(@mon[5] + @tue[5] + @wed[5] + @thu[5] + @fri[5] + @sat[5] + @sun[5]) %></strong></td>
        <td><strong><%= number_to_currency(@mon[6] + @tue[6] + @wed[6] + @thu[6] + @fri[6] + @sat[6] + @sun[6]) %></strong></td>
        <td><strong><%= number_to_currency(@mon[7] + @tue[7] + @wed[7] + @thu[7] + @fri[7] + @sat[7] + @sun[7]) %></strong></td>
        <td><strong><%= number_to_currency(@mon[8] + @tue[8] + @wed[8] + @thu[8] + @fri[8] + @sat[8] + @sun[8]) %></strong></td>
        <td><strong><%= number_to_currency(@mon[9] + @tue[9] + @wed[9] + @thu[9] + @fri[9] + @sat[9] + @sun[9]) %></strong></td>
      </tr>
    </table>



  </div>
</div>




<br></br>
<%#= render( :partial => 'week_table_2') %>
<%#= render( :partial => 'week_table_test') %>
<!-- B: <%= @week_b_2.strftime('%a %-m/%-d/%y') %> -->
<!-- E: <%= @week_e_2.strftime('%a %-m/%-d/%y') %> -->
<!-- <p><%= @weeks %></p> -->
</br>
<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @sale.day %>
</p>

<p>
  <strong>Sequoia:</strong>
  <%= @sale.sequoia %>
</p>

<p>
  <strong>Empire:</strong>
  <%= @sale.empire %>
</p>

<p>
  <strong>Pacific:</strong>
  <%= @sale.pacific %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>